# frozen_string_literal: true

# Loads AppstoreWebhooks testing helpers and factories
#
# This file is generated by `rails generate appstore_webhooks:setup`
#
# Provides:
#   - encode_apple_jws helper for creating test JWS tokens
#   - :apple_transaction_payload factory
#   - :apple_renewal_payload factory
#   - :signed_apple_webhook factory (complete webhook payload)
#
# Usage in specs:
#   webhook = build(:signed_apple_webhook, app_account_token: user.app_account_token)
#   post '/api/v1/appstore_webhooks', params: webhook, as: :json

require "appstore_webhooks/testing"

if defined?(RSpec)
  RSpec.configure do |config|
    config.include AppstoreWebhooks::Testing::ApplePayloadHelper, type: :request
  end
end

ActiveSupport::TestCase.include AppstoreWebhooks::Testing::ApplePayloadHelper if defined?(ActiveSupport::TestCase)
